name: Analyse SonarQube Latest

on:
  push:
    branches: ['main', 'develop', 'feature/*', 'bugfix/*']  

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 
            10.0
          
      - name: Install SonarQube
        run: dotnet tool install --global dotnet-sonarscanner
        
      - name: Start SonarQube scan
        run: | 
          dotnet sonarscanner begin \
            /k:"ballware_ballware-shared-dotnet" \
            /o:"ballware" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" \
            /d:sonar.exclusions="**/Migrations/**/*"
          
      - name: Restore dependencies
        run: dotnet restore ballware-shared.sln            
          
      - name: Build solution
        run: dotnet build ballware-shared.sln --no-incremental --configuration Release

      - name: Run coverage for all test projects        
        run: |
          dotnet test ballware-shared.sln --no-build --configuration Release \
            --collect:"XPlat Code Coverage" \
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover      
        
      - name: End SonarQube scan
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}" 
